### ISSUE TITLE
Mappings no longer work

### ISSUE THREAD

**Issue by andymcguinness** [freitass/todo.txt-vim#35]
First off, gotta say I love this plugin. Thanks for it! It's definitely been a great addition to my arsenal!

However, after the last update, mappings no longer seem to be working. Is there something I can test to make sure that it's not just me? It's happening on more than one of my machines.

Thanks,
Andy

**Comment by freitass** [comment]
Hi Andy,

Thank you for the feedback. As it was suggested on issue #28 (and as recommended by vim's documentation), all mapping were changed to use `<localleader>` instead of `<leader>`. If you don't have maplocalleader set on your environment then your '<localleader>` is probably `\`. For more information on that regard, please check `:h <Localleader>`.

Leandro

**Comment by andymcguinness** [comment]
Ah, that was it, I didn't have that set. Thanks a lot!
