### ISSUE TITLE
Highlight overdue tasks

### ISSUE THREAD

**Issue by nikolay-turpitko** [freitass/todo.txt-vim#44]
Currently all dates are highlight using regexp, but it would be cool to highlight overdue dates as Error, for example. Preferably, only dates with "due:" prefix.

**Comment by victal** [comment]
Hello,

I don't know much vimscript but judging from what I read in the docs, syntax highlighting works by matching the text with a keyword or pattern.

So I ended up implementing this highlight, but ended up using an external python script to generate the correct regexp for the date, which also means it won't work in a Vim installation without the `+python` option.

If that's not an issue I can send in a PR with the changes (or since I don't know vimscript that well, if someone knows a better way to do this, please tell!).

**Comment by freitass** [comment]
@victal I'm not sure it can be done in vimscript without a great complexity involved. The python solution is welcome if the plugin would still work (except for this feature, of course) for users without the `+python` option.

**Comment by nikolay-turpitko** [comment]
@victal @freitass Thanks, guys! Works perfectly!

**Comment by thioshp** [comment]
Wish overdue dates didn't depend on Vim's python support.
